### ISSUE TITLE
Aplicação de Paginação 

### ISSUE THREAD

**Issue by otaviosouza21** [FelJohnny/rh-newsletter-front#1]
Discução de metodos de paginação,  pesquisei alguns metodos diferentes, e algumas aulas do youtube, podemos entender e definir o melhor metodo:

**Video que me ajudou a entender o coinceito de paginação e como aplicar em REACT JS:**

https://www.youtube.com/watch?v=v91BLoapVDw

**Esta consulta no chatGPT explique a importancia de realizaar issues no projeto, e tambem uma aplicação de paginação utilizando alguns metodos diferentes:**
https://chat.openai.com/share/6afa028c-3cfa-40cf-be9f-bf094178d9eb

**Comment by FelJohnny** [comment]
Vamos validar a inclusão do scroll infinito ao inves de paginação
